kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb1
subjects:
  - kind: ServiceAccount
    name: benoixdemacadamia
    namespace: default
roleRef:
  kind: ClusterRole
  name: cr1
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb2
subjects:
  - kind: ServiceAccount
    name: clusteradmin
    namespace: default
roleRef:
  kind: ClusterRole
  name: clusteradmin1
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb3
subjects:
  - kind: ServiceAccount
    name: sysops
    namespace: default
roleRef:
  kind: ClusterRole
  name: sysops1
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb4
subjects:
  - kind: ServiceAccount
    name: dev
    namespace: default
roleRef:
  kind: ClusterRole
  name: dev1
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: crb5
subjects:
  - kind: ServiceAccount
    name: cli
    namespace: default
roleRef:
  kind: ClusterRole
  name: cli1
  apiGroup: rbac.authorization.k8s.io